name: Task 5

on:
  issues:
    types: [opened]
  workflow_dispatch: 

jobs:
  job1:
    runs-on: ubuntu-latest
    steps: 
      - uses: Azure/login@v1    
        with:
            creds: ${{ secrets.AZURE_SERVICEPRINCIPAL_CREDS }}
      
