name: Docker Image CI

on:
  push:
    branches: [ "main" ]

env:
  registryName: haduongdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: ./Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ${{ env.dockerFolderPath }} --file Dockerfile --tag team9:${{ env.tag }}
